# Generated by Django 3.1.1 on 2021-01-24 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='図鑑ナンバー')),
                ('name_jpn', models.CharField(max_length=255, verbose_name='名前')),
                ('name_eng', models.CharField(max_length=255, verbose_name='名前(英語)')),
                ('classification', models.CharField(max_length=255, verbose_name='分類')),
                ('type1', models.CharField(max_length=255, verbose_name='タイプ1')),
                ('type2', models.CharField(max_length=255, null=True, verbose_name='タイプ2')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='高さ')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='重さ')),
                ('ability1', models.CharField(max_length=255, verbose_name='特性1')),
                ('ability2', models.CharField(max_length=255, null=True, verbose_name='特性2')),
                ('hidden_ability', models.CharField(max_length=255, null=True, verbose_name='夢特性')),
                ('detail', models.TextField(max_length=500, verbose_name='図鑑説明')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='PredictedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Predicts',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False, verbose_name='判別ID')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pokemon')),
            ],
        ),
    ]
