# Generated by Django 3.1.1 on 2021-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='画像'),
        ),
    ]
