# Generated by Django 3.1.1 on 2020-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='voice',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.FilePathField(blank=True, verbose_name='画像'),
        ),
    ]
