# Generated by Django 3.1.1 on 2021-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210125_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='画像'),
        ),
    ]
