# Generated by Django 3.1.1 on 2020-11-30 06:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201130_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='画像'),
        ),
    ]
