# Generated by Django 3.1.1 on 2021-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210125_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.AlterField(
            model_name='predicts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
