# Generated by Django 3.1.1 on 2021-01-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210125_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='detail',
        ),
    ]
