# Generated by Django 3.1.1 on 2020-12-07 02:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201207_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像'),
        ),
    ]
