# Generated by Django 3.1.1 on 2020-12-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201207_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=255, verbose_name='名前')),
                ('email', models.CharField(max_length=255, verbose_name='Eメール')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default=999, upload_to='images', verbose_name='画像'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Predicts',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False, verbose_name='判別ID')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pokemon')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
