# Generated by Django 3.1.1 on 2020-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicts',
            name='user_email',
            field=models.CharField(max_length=255, verbose_name='Eメール'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
