# Generated by Django 3.1.1 on 2020-12-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201213_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicts',
            old_name='pokemon_number',
            new_name='pokemon_id',
        ),
    ]
