# Generated by Django 3.1.1 on 2020-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201214_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicts',
            name='user_email',
            field=models.CharField(max_length=500, verbose_name='Eメール'),
        ),
    ]
